version: '3.3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - client-build:/var/www/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  redis:
    container_name: redis
    image: redis

  client:
    build: ./client
    volumes:
      - client-build:/build

  backend:
    container_name: backend
    build: ./backend
    restart: always

volumes:
  client-build: